### ISSUE TITLE
如果没做好就不要放上去，浪费搜索人的经历。

### ISSUE THREAD

**Issue by xiaya** [RenSihao/ALYEmotionsKeyBoardView#1]

**Comment by RenSihao** [comment]
有一天你走在路上，突然觉得很渴，正好旁边有一家免费提供饮用水的店铺，你很开心，走进去喝了一一杯，然后吧唧着嘴，妈的还是饮料好喝，差评！然后拍拍屁股，大摇大摆走了出去。
